# cloudbuild.yaml (Na raiz do repositório hp/)
# cloudbuild.yaml (Adicione esta seção no início)
options:
  logging: CLOUD_LOGGING_ONLY # Força o logging a ir apenas para o Cloud Logging,
                             # contornando a exigência do logs_bucket.

steps:
# 1. Constrói a imagem Docker a partir do subdiretório hp-ingestion
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'hp-ingestion/Dockerfile',  # Especifica ONDE está o arquivo
    '-t', 'gcr.io/$PROJECT_ID/${_hp-ingestion}-image',
    '.'
  ]
# 2. Faz o deploy da imagem no Cloud Run
- id: 'DEPLOY SERVICE'
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', '${_hp-ingestion-runner}',
    '--image', 'gcr.io/$PROJECT_ID/${_hp-ingestion}-image',
    '--region', '${_us-central1},
    '--platform', 'managed',
    '--allow-unauthenticated', 
    '--timeout', '1800',
    '--memory', '512Mi',
    '--set-env-vars', 'INSTANCE_ID=${_demo-hp},DATABASE_ID=${_hp-database},GCP_PROJECT=${_PROJECT_ID},REGION=${_us-central1$}'
    '--vpc-connector', 'spanner-connector' 
  ]
images:
  - 'gcr.io/$PROJECT_ID/${_hp-ingestion}-image'
